version: 2.1
jobs:
  black:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: ensure black
          command: |
            pip install --user black
            ~/.local/bin/black --check ./freshchat ./tests

  lint:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: ensure flake8
          command: |
            pip install --user flake8
            ~/.local/bin/flake8 ./freshchat ./tests

  test:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --user --upgrade pip
            pip install --user --upgrade poetry tox tox-venv
      - run:
          name: run tests
          command: |
            ~/.local/bin/tox
      - persist_to_workspace:
          root: coverage
          paths:
            - html
            - coverage.xml
      - store_artifacts:
          path: coverage

  publish:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: publish python wheel
          command: |
            pip install poetry
            poetry config repositories.twyla $PYPI_REPO_URL
            poetry config http-basic.twyla $PYPI_REPO_USERNAME $PYPI_REPO_PASSWORD
            poetry publish --build -r twyla

workflows:
  ci-checks:
    jobs:
      - black
      - lint
      - test
      - publish:
          name: publish-pre-release-package
          context: Build
          requires:
            - black
            - lint
            - test
          filters:
            branches:
              only:
                - master
  release:
    jobs:
      - publish:
          name: publish-release-package
          context: Build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/